---
- name: Wait for connection
  win_wait_for:
    host: "{{ domain }}"
    port: 389
    sleep: 3

- name: Domain Join
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "{{ azurevmuser }}@{{ domain }}"
    domain_admin_password: "{{ azurevmpw }}"
    state: domain
  register: domain_join

- name: Reboot Server
  win_reboot:
  when: domain_join.reboot_required